delete from kos0514_com.m_skill;
insert into kos0514_com.m_skill(skill_field_code,skill_name,category,skill_level,experience_ym) values 
    ('Backend','.NET Framework','フレームワーク',3,1.5)
  , ('Backend','C#','プログラミング言語',2,0.5)
  , ('Backend','Caché','データベース',3,1.5)
  , ('Backend','Java','プログラミング言語',4,4.0)
  , ('Backend','Microsoft SQL Server','データベース',2,0.5)
  , ('Backend','MyBatis','O/Rマッパー',4,4.0)
  , ('Backend','MySQL','データベース',4,2.0)
  , ('Backend','Oracle Database','データベース',2,0.5)
  , ('Backend','Perl','プログラミング言語',2,0.5)
  , ('Backend','PHP','プログラミング言語',2,0.5)
  , ('Backend','PostgreSQL','データベース',4,2.0)
  , ('Backend','PowerShell','スクリプト言語',3,0.5)
  , ('Backend','Spring Boot','フレームワーク',4,3.0)
  , ('Backend','VB.NET','プログラミング言語',4,1.5)
  , ('Backend','VBA(Visual Basic for Applications)','プログラミング言語',4,1.0)
  , ('DevOps','Amazon Web Services','クラウド',1,0.5)
  , ('DevOps','Apache Subversion','バージョン管理',4,1.5)
  , ('DevOps','Docker','コンテナ',1,0.5)
  , ('DevOps','Docker Compose','コンテナ',1,0.5)
  , ('DevOps','Git','バージョン管理',4,3.0)
  , ('DevOps','GitHub','バージョン管理',4,3.0)
  , ('DevOps','nginx','Webサーバ',1,0.5)
  , ('DevOps','Vagrant','仮想環境',2,0.5)
  , ('Frontend','Apache Velocity','テンプレートエンジン',4,2.0)
  , ('Frontend','JavaScript','スクリプト言語',3,2.0)
  , ('Frontend','jQuery','JavaScriptライブラリ',3,1.5)
  , ('Frontend','JSP(JavaServer Page)','テンプレートエンジン',4,1.0)
  , ('Frontend','MUI(‎Material-UI)','デザインライブラリ',1,0.5)
  , ('Frontend','React','JavaScriptライブラリ',1,0.5)
  , ('Frontend','TypeScript','プログラミング言語',1,0.5);
