package com.app.ecotiya.domain.entity;

public class MInquiryKinds {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_inquiry_kinds.inquiry_kind_code
   *
   * @mbg.generated
   */
  private String inquiryKindCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_inquiry_kinds.inquiry_kind_name
   *
   * @mbg.generated
   */
  private String inquiryKindName;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_inquiry_kinds.sortno
   *
   * @mbg.generated
   */
  private Integer sortno;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_inquiry_kinds.inquiry_kind_code
   *
   * @return the value of m_inquiry_kinds.inquiry_kind_code
   * @mbg.generated
   */
  public String getInquiryKindCode() {
    return inquiryKindCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_inquiry_kinds.inquiry_kind_code
   *
   * @param inquiryKindCode the value for m_inquiry_kinds.inquiry_kind_code
   * @mbg.generated
   */
  public void setInquiryKindCode(String inquiryKindCode) {
    this.inquiryKindCode = inquiryKindCode == null ? null : inquiryKindCode.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_inquiry_kinds.inquiry_kind_name
   *
   * @return the value of m_inquiry_kinds.inquiry_kind_name
   * @mbg.generated
   */
  public String getInquiryKindName() {
    return inquiryKindName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_inquiry_kinds.inquiry_kind_name
   *
   * @param inquiryKindName the value for m_inquiry_kinds.inquiry_kind_name
   * @mbg.generated
   */
  public void setInquiryKindName(String inquiryKindName) {
    this.inquiryKindName = inquiryKindName == null ? null : inquiryKindName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_inquiry_kinds.sortno
   *
   * @return the value of m_inquiry_kinds.sortno
   * @mbg.generated
   */
  public Integer getSortno() {
    return sortno;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_inquiry_kinds.sortno
   *
   * @param sortno the value for m_inquiry_kinds.sortno
   * @mbg.generated
   */
  public void setSortno(Integer sortno) {
    this.sortno = sortno;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_inquiry_kinds
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    MInquiryKinds other = (MInquiryKinds) that;
    return (this.getInquiryKindCode() == null
            ? other.getInquiryKindCode() == null
            : this.getInquiryKindCode().equals(other.getInquiryKindCode()))
        && (this.getInquiryKindName() == null
            ? other.getInquiryKindName() == null
            : this.getInquiryKindName().equals(other.getInquiryKindName()))
        && (this.getSortno() == null
            ? other.getSortno() == null
            : this.getSortno().equals(other.getSortno()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_inquiry_kinds
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result =
        prime * result + ((getInquiryKindCode() == null) ? 0 : getInquiryKindCode().hashCode());
    result =
        prime * result + ((getInquiryKindName() == null) ? 0 : getInquiryKindName().hashCode());
    result = prime * result + ((getSortno() == null) ? 0 : getSortno().hashCode());
    return result;
  }
}
