package com.app.kos0514.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.app.kos0514.domain.entity.MInquiryKinds;

@Mapper
public interface MInquiryKindsMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_inquiry_kinds
   *
   * @mbg.generated
   */
  int insert(MInquiryKinds row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_inquiry_kinds
   *
   * @mbg.generated
   */
  int insertSelective(MInquiryKinds row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_inquiry_kinds
   *
   * @mbg.generated
   */
  MInquiryKinds selectByPrimaryKey(String inquiryKindCode);

  /**
   * Select all records from database.
   *
   * @return all records stored in database
   */
  List<MInquiryKinds> selectAll();
}
