package com.app.kos0514.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.app.kos0514.domain.entity.MSectionComment;

@Mapper
public interface MSectionCommentMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_section_comment
   *
   * @mbg.generated
   */
  int insert(MSectionComment row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_section_comment
   *
   * @mbg.generated
   */
  int insertSelective(MSectionComment row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_section_comment
   *
   * @mbg.generated
   */
  MSectionComment selectByPrimaryKey(
      @Param("sectionKindCode") String sectionKindCode,
      @Param("sectionCommentLine") Integer sectionCommentLine);

  /**
   * Select all records from database.
   *
   * @return all records stored in database
   */
  List<MSectionComment> selectAll();
}
