package ecotiya.com.domain.model;

import java.util.Date;

public class TSiteComment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_comment.comment_id
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_comment.coment_kind_code
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    private String comentKindCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_comment.created_at
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_comment.updated_at
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_site_comment.contents
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    private String contents;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_comment.comment_id
     *
     * @return the value of t_site_comment.comment_id
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_comment.comment_id
     *
     * @param commentId the value for t_site_comment.comment_id
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_comment.coment_kind_code
     *
     * @return the value of t_site_comment.coment_kind_code
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public String getComentKindCode() {
        return comentKindCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_comment.coment_kind_code
     *
     * @param comentKindCode the value for t_site_comment.coment_kind_code
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public void setComentKindCode(String comentKindCode) {
        this.comentKindCode = comentKindCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_comment.created_at
     *
     * @return the value of t_site_comment.created_at
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_comment.created_at
     *
     * @param createdAt the value for t_site_comment.created_at
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_comment.updated_at
     *
     * @return the value of t_site_comment.updated_at
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_comment.updated_at
     *
     * @param updatedAt the value for t_site_comment.updated_at
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_site_comment.contents
     *
     * @return the value of t_site_comment.contents
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public String getContents() {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_site_comment.contents
     *
     * @param contents the value for t_site_comment.contents
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    public void setContents(String contents) {
        this.contents = contents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TSiteComment other = (TSiteComment) that;
        return (this.getCommentId() == null ? other.getCommentId() == null : this.getCommentId().equals(other.getCommentId()))
            && (this.getComentKindCode() == null ? other.getComentKindCode() == null : this.getComentKindCode().equals(other.getComentKindCode()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()))
            && (this.getContents() == null ? other.getContents() == null : this.getContents().equals(other.getContents()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCommentId() == null) ? 0 : getCommentId().hashCode());
        result = prime * result + ((getComentKindCode() == null) ? 0 : getComentKindCode().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        result = prime * result + ((getContents() == null) ? 0 : getContents().hashCode());
        return result;
    }
}