package com.app.ecotiya.domain.mapper;

import com.app.ecotiya.domain.model.MInquiryKinds;
import com.app.ecotiya.domain.model.MInquiryKindsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MInquiryKindsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    long countByExample(MInquiryKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int deleteByExample(MInquiryKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int deleteByPrimaryKey(String inquiryKindCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int insert(MInquiryKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int insertSelective(MInquiryKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    List<MInquiryKinds> selectByExample(MInquiryKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    MInquiryKinds selectByPrimaryKey(String inquiryKindCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByExampleSelective(@Param("row") MInquiryKinds row, @Param("example") MInquiryKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByExample(@Param("row") MInquiryKinds row, @Param("example") MInquiryKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByPrimaryKeySelective(MInquiryKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_inquiry_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByPrimaryKey(MInquiryKinds row);
}