package com.app.ecotiya.domain.mapper;

import com.app.ecotiya.domain.model.MSkillDivision;
import com.app.ecotiya.domain.model.MSkillDivisionExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSkillDivisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    long countByExample(MSkillDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int deleteByExample(MSkillDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int deleteByPrimaryKey(Integer skillDivisionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int insert(MSkillDivision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int insertSelective(MSkillDivision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    List<MSkillDivision> selectByExample(MSkillDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    MSkillDivision selectByPrimaryKey(Integer skillDivisionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByExampleSelective(@Param("row") MSkillDivision row, @Param("example") MSkillDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByExample(@Param("row") MSkillDivision row, @Param("example") MSkillDivisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByPrimaryKeySelective(MSkillDivision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    int updateByPrimaryKey(MSkillDivision row);
}