package com.app.ecotiya.domain.mapper;

import com.app.ecotiya.domain.model.TSiteComment;
import com.app.ecotiya.domain.model.TSiteCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TSiteCommentMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    long countByExample (TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int deleteByExample (TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int deleteByPrimaryKey (Long commentId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int insert (TSiteComment row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int insertSelective (TSiteComment row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    List<TSiteComment> selectByExampleWithBLOBs (TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    List<TSiteComment> selectByExample (TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    TSiteComment selectByPrimaryKey (Long commentId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int updateByExampleSelective (@Param ("row") TSiteComment row, @Param ("example") TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int updateByExampleWithBLOBs (@Param ("row") TSiteComment row, @Param ("example") TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int updateByExample (@Param ("row") TSiteComment row, @Param ("example") TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int updateByPrimaryKeySelective (TSiteComment row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs (TSiteComment row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_site_comment
     * @mbg.generated
     */
    int updateByPrimaryKey (TSiteComment row);
}