package ecotiya.com.domain.mapper;

import ecotiya.com.domain.model.MSiteCommentKinds;
import ecotiya.com.domain.model.MSiteCommentKindsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSiteCommentKindsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    long countByExample(MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int deleteByExample(MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int deleteByPrimaryKey(String comentKindCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int insert(MSiteCommentKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int insertSelective(MSiteCommentKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    List<MSiteCommentKinds> selectByExample(MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    MSiteCommentKinds selectByPrimaryKey(String comentKindCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExampleSelective(@Param("row") MSiteCommentKinds row, @Param("example") MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExample(@Param("row") MSiteCommentKinds row, @Param("example") MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKeySelective(MSiteCommentKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKey(MSiteCommentKinds row);
}