package ecotiya.com.domain.mapper;

import ecotiya.com.domain.model.MSkillField;
import ecotiya.com.domain.model.MSkillFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSkillFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    long countByExample(MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int deleteByExample(MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int deleteByPrimaryKey(Integer skillFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int insert(MSkillField row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int insertSelective(MSkillField row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    List<MSkillField> selectByExample(MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    MSkillField selectByPrimaryKey(Integer skillFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExampleSelective(@Param("row") MSkillField row, @Param("example") MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExample(@Param("row") MSkillField row, @Param("example") MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKeySelective(MSkillField row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKey(MSkillField row);
}