package ecotiya.com.domain.mapper;

import ecotiya.com.domain.model.TInquiryLists;
import ecotiya.com.domain.model.TInquiryListsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TInquiryListsMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    long countByExample (TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int deleteByExample (TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int deleteByPrimaryKey (Long inquiryId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int insert (TInquiryLists row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int insertSelective (TInquiryLists row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    List<TInquiryLists> selectByExampleWithBLOBs (TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    List<TInquiryLists> selectByExample (TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    TInquiryLists selectByPrimaryKey (Long inquiryId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int updateByExampleSelective (@Param ("row") TInquiryLists row, @Param ("example") TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int updateByExampleWithBLOBs (@Param ("row") TInquiryLists row, @Param ("example") TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int updateByExample (@Param ("row") TInquiryLists row, @Param ("example") TInquiryListsExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKeySelective (TInquiryLists row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKeyWithBLOBs (TInquiryLists row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated  Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKey (TInquiryLists row);
}