package ecotiya.com.domain.mapper;

import ecotiya.com.domain.model.TSiteComment;
import ecotiya.com.domain.model.TSiteCommentExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TSiteCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    long countByExample(TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int deleteByExample(TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int deleteByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int insert(TSiteComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int insertSelective(TSiteComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    List<TSiteComment> selectByExampleWithBLOBs(TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    List<TSiteComment> selectByExample(TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    TSiteComment selectByPrimaryKey(Long commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExampleSelective(@Param("row") TSiteComment row, @Param("example") TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExampleWithBLOBs(@Param("row") TSiteComment row, @Param("example") TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByExample(@Param("row") TSiteComment row, @Param("example") TSiteCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKeySelective(TSiteComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKeyWithBLOBs(TSiteComment row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_site_comment
     *
     * @mbg.generated Thu May 12 17:12:38 JST 2022
     */
    int updateByPrimaryKey(TSiteComment row);
}