package com.app.ecotiya.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.app.ecotiya.domain.entity.MCareer;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MCareerMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  int insert(MCareer row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  int insertSelective(MCareer row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  MCareer selectByPrimaryKey(
      @Param("careerDate") String careerDate, @Param("careerDivision") String careerDivision);

  /**
   * Select all records from database.
   *
   * @return all records stored in database
   */
  List<MCareer> selectAll();
}
