package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.MInquiryKinds;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MInquiryKindsMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table m_inquiry_kinds
     * @mbg.generated
     */
    int deleteByPrimaryKey (String inquiryKindCode);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table m_inquiry_kinds
     * @mbg.generated
     */
    int insert (MInquiryKinds row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table m_inquiry_kinds
     * @mbg.generated
     */
    int insertSelective (MInquiryKinds row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table m_inquiry_kinds
     * @mbg.generated
     */
    MInquiryKinds selectByPrimaryKey (String inquiryKindCode);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table m_inquiry_kinds
     * @mbg.generated
     */
    int updateByPrimaryKeySelective (MInquiryKinds row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table m_inquiry_kinds
     * @mbg.generated
     */
    int updateByPrimaryKey (MInquiryKinds row);
}