package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.MSiteCommentKinds;
import com.app.ecotiya.domain.entity.MSiteCommentKindsExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSiteCommentKindsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    long countByExample(MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int deleteByExample(MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String comentKindCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int insert(MSiteCommentKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int insertSelective(MSiteCommentKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    List<MSiteCommentKinds> selectByExample(MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    MSiteCommentKinds selectByPrimaryKey(String comentKindCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MSiteCommentKinds row, @Param("example") MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MSiteCommentKinds row, @Param("example") MSiteCommentKindsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MSiteCommentKinds row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MSiteCommentKinds row);
}