package com.app.ecotiya.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.app.ecotiya.domain.entity.MSiteComment;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSiteCommentMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  int insert(MSiteComment row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  int insertSelective(MSiteComment row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  MSiteComment selectByPrimaryKey(
      @Param("commentKindCode") String commentKindCode, @Param("commentLine") Integer commentLine);

  /**
   * Select all records from database.
   *
   * @return all records stored in database
   */
  List<MSiteComment> selectAll();
}
