package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.MSkill;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MSkillMapper {
  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  int insert(MSkill row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  int insertSelective(MSkill row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  MSkill selectByPrimaryKey(Integer skillId);
}
