package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.MSkillField;
import com.app.ecotiya.domain.entity.MSkillFieldExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSkillFieldMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    long countByExample(MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int deleteByExample(MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer skillFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int insert(MSkillField row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int insertSelective(MSkillField row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    List<MSkillField> selectByExample(MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    MSkillField selectByPrimaryKey(Integer skillFieldId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") MSkillField row, @Param("example") MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") MSkillField row, @Param("example") MSkillFieldExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MSkillField row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_field
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MSkillField row);
}