package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.MSkillDivision;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface MSkillDivisionMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill_division
   *
   * @mbg.generated
   */
  int insert(MSkillDivision row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill_division
   *
   * @mbg.generated
   */
  int insertSelective(MSkillDivision row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill_division
   *
   * @mbg.generated
   */
  MSkillDivision selectByPrimaryKey(Integer skillDivisionId);
}
