package com.app.ecotiya.domain.repository;

import org.apache.ibatis.annotations.Mapper;

import com.app.ecotiya.domain.entity.MSkillDivision;

@Mapper
public interface MSkillDivisionMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table m_skill_division
   * @mbg.generated
   */int deleteByPrimaryKey(Integer skillDivisionId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table m_skill_division
   * @mbg.generated
   */int insert(MSkillDivision row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table m_skill_division
   * @mbg.generated
   */int insertSelective(MSkillDivision row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table m_skill_division
   * @mbg.generated
   */MSkillDivision selectByPrimaryKey(Integer skillDivisionId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table m_skill_division
   * @mbg.generated
   */int updateByPrimaryKeySelective(MSkillDivision row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table m_skill_division
   * @mbg.generated
   */int updateByPrimaryKey(MSkillDivision row);
}