package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.TCareer;
import com.app.ecotiya.domain.entity.TCareerExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TCareerMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    long countByExample (TCareerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int deleteByExample (TCareerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int deleteByPrimaryKey (Long careerId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int insert (TCareer row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int insertSelective (TCareer row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    List<TCareer> selectByExample (TCareerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    TCareer selectByPrimaryKey (Long careerId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int updateByExampleSelective (@Param ("row") TCareer row, @Param ("example") TCareerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int updateByExample (@Param ("row") TCareer row, @Param ("example") TCareerExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int updateByPrimaryKeySelective (TCareer row);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    int updateByPrimaryKey (TCareer row);
}