package com.app.ecotiya.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.app.ecotiya.domain.entity.TCareer;

@Mapper
public interface TCareerMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
   * @mbg.generated
   */int deleteByPrimaryKey(Integer careerId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
   * @mbg.generated
   */int insert(TCareer row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
   * @mbg.generated
   */int insertSelective(TCareer row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
   * @mbg.generated
   */TCareer selectByPrimaryKey(Integer careerId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
   * @mbg.generated
   */int updateByPrimaryKeySelective(TCareer row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
   * @mbg.generated
   */int updateByPrimaryKey(TCareer row);

/**
   * Select all records from database.
   *
   * @return all records stored in database
   */
  List<TCareer> selectAll();
}
