package com.app.ecotiya.domain.repository;

import com.app.ecotiya.domain.entity.TSkill;
import com.app.ecotiya.domain.entity.TSkillExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TSkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    long countByExample(TSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int deleteByExample(TSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int insert(TSkill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int insertSelective(TSkill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    List<TSkill> selectByExample(TSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    TSkill selectByPrimaryKey(Long skillId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TSkill row, @Param("example") TSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TSkill row, @Param("example") TSkillExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSkill row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_skill
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSkill row);
}