package com.app.ecotiya.domain.repository;

import org.apache.ibatis.annotations.Mapper;

import com.app.ecotiya.domain.entity.TUsers;

@Mapper
public interface TUsersMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  int deleteByPrimaryKey(Long userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  int insert(TUsers row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  int insertSelective(TUsers row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  TUsers selectByPrimaryKey(Long userId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  int updateByPrimaryKeySelective(TUsers row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  int updateByPrimaryKey(TUsers row);
}
