package com.app.ecotiya.domain.repository;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.app.ecotiya.domain.entity.MSkill;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface MSkillMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  int insert(MSkill row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  int insertSelective(MSkill row);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  MSkill selectByPrimaryKey(
      @Param("skillFieldCode") String skillFieldCode, @Param("skillName") String skillName);

  /**
   * Select all records from database.
   *
   * @return all records stored in database
   */
  List<MSkill> selectAll();
}
