package com.app.ecotiya.domain.entity;

import java.time.LocalDateTime;

public class MCareer {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.career_id
   *
   * @mbg.generated
   */
  private Integer careerId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.datetime
   *
   * @mbg.generated
   */
  private LocalDateTime datetime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.title
   *
   * @mbg.generated
   */
  private String title;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.contents
   *
   * @mbg.generated
   */
  private String contents;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.career_id
   *
   * @return the value of m_career.career_id
   * @mbg.generated
   */
  public Integer getCareerId() {
    return careerId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.career_id
   *
   * @param careerId the value for m_career.career_id
   * @mbg.generated
   */
  public void setCareerId(Integer careerId) {
    this.careerId = careerId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.datetime
   *
   * @return the value of m_career.datetime
   * @mbg.generated
   */
  public LocalDateTime getDatetime() {
    return datetime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.datetime
   *
   * @param datetime the value for m_career.datetime
   * @mbg.generated
   */
  public void setDatetime(LocalDateTime datetime) {
    this.datetime = datetime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.title
   *
   * @return the value of m_career.title
   * @mbg.generated
   */
  public String getTitle() {
    return title;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.title
   *
   * @param title the value for m_career.title
   * @mbg.generated
   */
  public void setTitle(String title) {
    this.title = title == null ? null : title.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.contents
   *
   * @return the value of m_career.contents
   * @mbg.generated
   */
  public String getContents() {
    return contents;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.contents
   *
   * @param contents the value for m_career.contents
   * @mbg.generated
   */
  public void setContents(String contents) {
    this.contents = contents == null ? null : contents.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    MCareer other = (MCareer) that;
    return (this.getCareerId() == null
            ? other.getCareerId() == null
            : this.getCareerId().equals(other.getCareerId()))
        && (this.getDatetime() == null
            ? other.getDatetime() == null
            : this.getDatetime().equals(other.getDatetime()))
        && (this.getTitle() == null
            ? other.getTitle() == null
            : this.getTitle().equals(other.getTitle()))
        && (this.getContents() == null
            ? other.getContents() == null
            : this.getContents().equals(other.getContents()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getCareerId() == null) ? 0 : getCareerId().hashCode());
    result = prime * result + ((getDatetime() == null) ? 0 : getDatetime().hashCode());
    result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
    result = prime * result + ((getContents() == null) ? 0 : getContents().hashCode());
    return result;
  }
}
