package com.app.ecotiya.domain.entity;

public class MCareer {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.career_date
   *
   * @mbg.generated
   */
  private String careerDate;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.career_division
   *
   * @mbg.generated
   */
  private String careerDivision;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.career_title
   *
   * @mbg.generated
   */
  private String careerTitle;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_career.career_contents
   *
   * @mbg.generated
   */
  private String careerContents;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.career_date
   *
   * @return the value of m_career.career_date
   * @mbg.generated
   */
  public String getCareerDate() {
    return careerDate;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.career_date
   *
   * @param careerDate the value for m_career.career_date
   * @mbg.generated
   */
  public void setCareerDate(String careerDate) {
    this.careerDate = careerDate == null ? null : careerDate.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.career_division
   *
   * @return the value of m_career.career_division
   * @mbg.generated
   */
  public String getCareerDivision() {
    return careerDivision;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.career_division
   *
   * @param careerDivision the value for m_career.career_division
   * @mbg.generated
   */
  public void setCareerDivision(String careerDivision) {
    this.careerDivision = careerDivision == null ? null : careerDivision.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.career_title
   *
   * @return the value of m_career.career_title
   * @mbg.generated
   */
  public String getCareerTitle() {
    return careerTitle;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.career_title
   *
   * @param careerTitle the value for m_career.career_title
   * @mbg.generated
   */
  public void setCareerTitle(String careerTitle) {
    this.careerTitle = careerTitle == null ? null : careerTitle.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_career.career_contents
   *
   * @return the value of m_career.career_contents
   * @mbg.generated
   */
  public String getCareerContents() {
    return careerContents;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_career.career_contents
   *
   * @param careerContents the value for m_career.career_contents
   * @mbg.generated
   */
  public void setCareerContents(String careerContents) {
    this.careerContents = careerContents == null ? null : careerContents.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    MCareer other = (MCareer) that;
    return (this.getCareerDate() == null
            ? other.getCareerDate() == null
            : this.getCareerDate().equals(other.getCareerDate()))
        && (this.getCareerDivision() == null
            ? other.getCareerDivision() == null
            : this.getCareerDivision().equals(other.getCareerDivision()))
        && (this.getCareerTitle() == null
            ? other.getCareerTitle() == null
            : this.getCareerTitle().equals(other.getCareerTitle()))
        && (this.getCareerContents() == null
            ? other.getCareerContents() == null
            : this.getCareerContents().equals(other.getCareerContents()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_career
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getCareerDate() == null) ? 0 : getCareerDate().hashCode());
    result = prime * result + ((getCareerDivision() == null) ? 0 : getCareerDivision().hashCode());
    result = prime * result + ((getCareerTitle() == null) ? 0 : getCareerTitle().hashCode());
    result = prime * result + ((getCareerContents() == null) ? 0 : getCareerContents().hashCode());
    return result;
  }
}
