package com.app.ecotiya.domain.entity;

public class MSiteComment {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.comment_kind_code
   *
   * @mbg.generated
   */
  private String commentKindCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.comment_line
   *
   * @mbg.generated
   */
  private Integer commentLine;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.comment_title
   *
   * @mbg.generated
   */
  private String commentTitle;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.comment_image
   *
   * @mbg.generated
   */
  private String commentImage;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.comment_contents
   *
   * @mbg.generated
   */
  private String commentContents;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.comment_kind_code
   *
   * @return the value of m_site_comment.comment_kind_code
   * @mbg.generated
   */
  public String getCommentKindCode() {
    return commentKindCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.comment_kind_code
   *
   * @param commentKindCode the value for m_site_comment.comment_kind_code
   * @mbg.generated
   */
  public void setCommentKindCode(String commentKindCode) {
    this.commentKindCode = commentKindCode == null ? null : commentKindCode.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.comment_line
   *
   * @return the value of m_site_comment.comment_line
   * @mbg.generated
   */
  public Integer getCommentLine() {
    return commentLine;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.comment_line
   *
   * @param commentLine the value for m_site_comment.comment_line
   * @mbg.generated
   */
  public void setCommentLine(Integer commentLine) {
    this.commentLine = commentLine;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.comment_title
   *
   * @return the value of m_site_comment.comment_title
   * @mbg.generated
   */
  public String getCommentTitle() {
    return commentTitle;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.comment_title
   *
   * @param commentTitle the value for m_site_comment.comment_title
   * @mbg.generated
   */
  public void setCommentTitle(String commentTitle) {
    this.commentTitle = commentTitle == null ? null : commentTitle.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.comment_image
   *
   * @return the value of m_site_comment.comment_image
   * @mbg.generated
   */
  public String getCommentImage() {
    return commentImage;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.comment_image
   *
   * @param commentImage the value for m_site_comment.comment_image
   * @mbg.generated
   */
  public void setCommentImage(String commentImage) {
    this.commentImage = commentImage == null ? null : commentImage.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.comment_contents
   *
   * @return the value of m_site_comment.comment_contents
   * @mbg.generated
   */
  public String getCommentContents() {
    return commentContents;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.comment_contents
   *
   * @param commentContents the value for m_site_comment.comment_contents
   * @mbg.generated
   */
  public void setCommentContents(String commentContents) {
    this.commentContents = commentContents == null ? null : commentContents.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    MSiteComment other = (MSiteComment) that;
    return (this.getCommentKindCode() == null
            ? other.getCommentKindCode() == null
            : this.getCommentKindCode().equals(other.getCommentKindCode()))
        && (this.getCommentLine() == null
            ? other.getCommentLine() == null
            : this.getCommentLine().equals(other.getCommentLine()))
        && (this.getCommentTitle() == null
            ? other.getCommentTitle() == null
            : this.getCommentTitle().equals(other.getCommentTitle()))
        && (this.getCommentImage() == null
            ? other.getCommentImage() == null
            : this.getCommentImage().equals(other.getCommentImage()))
        && (this.getCommentContents() == null
            ? other.getCommentContents() == null
            : this.getCommentContents().equals(other.getCommentContents()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result =
        prime * result + ((getCommentKindCode() == null) ? 0 : getCommentKindCode().hashCode());
    result = prime * result + ((getCommentLine() == null) ? 0 : getCommentLine().hashCode());
    result = prime * result + ((getCommentTitle() == null) ? 0 : getCommentTitle().hashCode());
    result = prime * result + ((getCommentImage() == null) ? 0 : getCommentImage().hashCode());
    result =
        prime * result + ((getCommentContents() == null) ? 0 : getCommentContents().hashCode());
    return result;
  }
}
