package com.app.ecotiya.domain.entity;

public class MSiteComment {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.coment_kind_code
   *
   * @mbg.generated
   */
  private String comentKindCode;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.coment_kind_name
   *
   * @mbg.generated
   */
  private String comentKindName;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.image
   *
   * @mbg.generated
   */
  private String image;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_site_comment.contents
   *
   * @mbg.generated
   */
  private String contents;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.coment_kind_code
   *
   * @return the value of m_site_comment.coment_kind_code
   * @mbg.generated
   */
  public String getComentKindCode() {
    return comentKindCode;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.coment_kind_code
   *
   * @param comentKindCode the value for m_site_comment.coment_kind_code
   * @mbg.generated
   */
  public void setComentKindCode(String comentKindCode) {
    this.comentKindCode = comentKindCode == null ? null : comentKindCode.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.coment_kind_name
   *
   * @return the value of m_site_comment.coment_kind_name
   * @mbg.generated
   */
  public String getComentKindName() {
    return comentKindName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.coment_kind_name
   *
   * @param comentKindName the value for m_site_comment.coment_kind_name
   * @mbg.generated
   */
  public void setComentKindName(String comentKindName) {
    this.comentKindName = comentKindName == null ? null : comentKindName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.image
   *
   * @return the value of m_site_comment.image
   * @mbg.generated
   */
  public String getImage() {
    return image;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.image
   *
   * @param image the value for m_site_comment.image
   * @mbg.generated
   */
  public void setImage(String image) {
    this.image = image == null ? null : image.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_site_comment.contents
   *
   * @return the value of m_site_comment.contents
   * @mbg.generated
   */
  public String getContents() {
    return contents;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_site_comment.contents
   *
   * @param contents the value for m_site_comment.contents
   * @mbg.generated
   */
  public void setContents(String contents) {
    this.contents = contents == null ? null : contents.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    MSiteComment other = (MSiteComment) that;
    return (this.getComentKindCode() == null
            ? other.getComentKindCode() == null
            : this.getComentKindCode().equals(other.getComentKindCode()))
        && (this.getComentKindName() == null
            ? other.getComentKindName() == null
            : this.getComentKindName().equals(other.getComentKindName()))
        && (this.getImage() == null
            ? other.getImage() == null
            : this.getImage().equals(other.getImage()))
        && (this.getContents() == null
            ? other.getContents() == null
            : this.getContents().equals(other.getContents()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_site_comment
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getComentKindCode() == null) ? 0 : getComentKindCode().hashCode());
    result = prime * result + ((getComentKindName() == null) ? 0 : getComentKindName().hashCode());
    result = prime * result + ((getImage() == null) ? 0 : getImage().hashCode());
    result = prime * result + ((getContents() == null) ? 0 : getContents().hashCode());
    return result;
  }
}
