package com.app.ecotiya.domain.entity;

import java.math.BigDecimal;

public class MSkill {
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_skill.skill_id
   *
   * @mbg.generated
   */
  private Integer skillId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_skill.skill_division_id
   *
   * @mbg.generated
   */
  private Integer skillDivisionId;

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * m_skill.experience_ym
   *
   * @mbg.generated
   */
  private BigDecimal experienceYm;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_skill.skill_id
   *
   * @return the value of m_skill.skill_id
   * @mbg.generated
   */
  public Integer getSkillId() {
    return skillId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_skill.skill_id
   *
   * @param skillId the value for m_skill.skill_id
   * @mbg.generated
   */
  public void setSkillId(Integer skillId) {
    this.skillId = skillId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_skill.skill_division_id
   *
   * @return the value of m_skill.skill_division_id
   * @mbg.generated
   */
  public Integer getSkillDivisionId() {
    return skillDivisionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_skill.skill_division_id
   *
   * @param skillDivisionId the value for m_skill.skill_division_id
   * @mbg.generated
   */
  public void setSkillDivisionId(Integer skillDivisionId) {
    this.skillDivisionId = skillDivisionId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column m_skill.experience_ym
   *
   * @return the value of m_skill.experience_ym
   * @mbg.generated
   */
  public BigDecimal getExperienceYm() {
    return experienceYm;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column m_skill.experience_ym
   *
   * @param experienceYm the value for m_skill.experience_ym
   * @mbg.generated
   */
  public void setExperienceYm(BigDecimal experienceYm) {
    this.experienceYm = experienceYm;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    MSkill other = (MSkill) that;
    return (this.getSkillId() == null
            ? other.getSkillId() == null
            : this.getSkillId().equals(other.getSkillId()))
        && (this.getSkillDivisionId() == null
            ? other.getSkillDivisionId() == null
            : this.getSkillDivisionId().equals(other.getSkillDivisionId()))
        && (this.getExperienceYm() == null
            ? other.getExperienceYm() == null
            : this.getExperienceYm().equals(other.getExperienceYm()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * m_skill
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getSkillId() == null) ? 0 : getSkillId().hashCode());
    result =
        prime * result + ((getSkillDivisionId() == null) ? 0 : getSkillDivisionId().hashCode());
    result = prime * result + ((getExperienceYm() == null) ? 0 : getExperienceYm().hashCode());
    return result;
  }
}
