package com.app.ecotiya.domain.entity;

import java.time.LocalDateTime;

import com.app.ecotiya.domain.entity.base.AppBaseEntity;

public class TUsers extends AppBaseEntity {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.user_id
   *
   * @mbg.generated
   */
  private Long userId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.user_name
   *
   * @mbg.generated
   */
  private String userName;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.mail_address
   *
   * @mbg.generated
   */
  private String mailAddress;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.password
   *
   * @mbg.generated
   */
  private String password;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.password_confirmation
   *
   * @mbg.generated
   */
  private String passwordConfirmation;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.admin
   *
   * @mbg.generated
   */
  private Boolean admin;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.icon
   *
   * @mbg.generated
   */
  private String icon;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column
   * t_users.temp_regist_flg
   *
   * @mbg.generated
   */
  private Boolean tempRegistFlg;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.user_id
   *
   * @return the value of t_users.user_id
   * @mbg.generated
   */
  public Long getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.user_id
   *
   * @param userId the value for t_users.user_id
   * @mbg.generated
   */
  public void setUserId(Long userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.user_name
   *
   * @return the value of t_users.user_name
   * @mbg.generated
   */
  public String getUserName() {
    return userName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.user_name
   *
   * @param userName the value for t_users.user_name
   * @mbg.generated
   */
  public void setUserName(String userName) {
    this.userName = userName == null ? null : userName.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.mail_address
   *
   * @return the value of t_users.mail_address
   * @mbg.generated
   */
  public String getMailAddress() {
    return mailAddress;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.mail_address
   *
   * @param mailAddress the value for t_users.mail_address
   * @mbg.generated
   */
  public void setMailAddress(String mailAddress) {
    this.mailAddress = mailAddress == null ? null : mailAddress.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.password
   *
   * @return the value of t_users.password
   * @mbg.generated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.password
   *
   * @param password the value for t_users.password
   * @mbg.generated
   */
  public void setPassword(String password) {
    this.password = password == null ? null : password.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.password_confirmation
   *
   * @return the value of t_users.password_confirmation
   * @mbg.generated
   */
  public String getPasswordConfirmation() {
    return passwordConfirmation;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.password_confirmation
   *
   * @param passwordConfirmation the value for t_users.password_confirmation
   * @mbg.generated
   */
  public void setPasswordConfirmation(String passwordConfirmation) {
    this.passwordConfirmation = passwordConfirmation == null ? null : passwordConfirmation.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.admin
   *
   * @return the value of t_users.admin
   * @mbg.generated
   */
  public Boolean getAdmin() {
    return admin;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.admin
   *
   * @param admin the value for t_users.admin
   * @mbg.generated
   */
  public void setAdmin(Boolean admin) {
    this.admin = admin;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.icon
   *
   * @return the value of t_users.icon
   * @mbg.generated
   */
  public String getIcon() {
    return icon;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.icon
   *
   * @param icon the value for t_users.icon
   * @mbg.generated
   */
  public void setIcon(String icon) {
    this.icon = icon == null ? null : icon.trim();
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database
   * column t_users.temp_regist_flg
   *
   * @return the value of t_users.temp_regist_flg
   * @mbg.generated
   */
  public Boolean getTempRegistFlg() {
    return tempRegistFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database
   * column t_users.temp_regist_flg
   *
   * @param tempRegistFlg the value for t_users.temp_regist_flg
   * @mbg.generated
   */
  public void setTempRegistFlg(Boolean tempRegistFlg) {
    this.tempRegistFlg = tempRegistFlg;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  @Override
  public boolean equals(Object that) {
    if (this == that) {
      return true;
    }
    if (that == null) {
      return false;
    }
    if (getClass() != that.getClass()) {
      return false;
    }
    TUsers other = (TUsers) that;
    return (this.getUserId() == null
            ? other.getUserId() == null
            : this.getUserId().equals(other.getUserId()))
        && (this.getUserName() == null
            ? other.getUserName() == null
            : this.getUserName().equals(other.getUserName()))
        && (this.getMailAddress() == null
            ? other.getMailAddress() == null
            : this.getMailAddress().equals(other.getMailAddress()))
        && (this.getPassword() == null
            ? other.getPassword() == null
            : this.getPassword().equals(other.getPassword()))
        && (this.getPasswordConfirmation() == null
            ? other.getPasswordConfirmation() == null
            : this.getPasswordConfirmation().equals(other.getPasswordConfirmation()))
        && (this.getAdmin() == null
            ? other.getAdmin() == null
            : this.getAdmin().equals(other.getAdmin()))
        && (this.getIcon() == null
            ? other.getIcon() == null
            : this.getIcon().equals(other.getIcon()))
        && (this.getTempRegistFlg() == null
            ? other.getTempRegistFlg() == null
            : this.getTempRegistFlg().equals(other.getTempRegistFlg()))
        && (this.getCreatedAt() == null
            ? other.getCreatedAt() == null
            : this.getCreatedAt().equals(other.getCreatedAt()))
        && (this.getUpdatedAt() == null
            ? other.getUpdatedAt() == null
            : this.getUpdatedAt().equals(other.getUpdatedAt()));
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table
   * t_users
   *
   * @mbg.generated
   */
  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
    result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
    result = prime * result + ((getMailAddress() == null) ? 0 : getMailAddress().hashCode());
    result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
    result =
        prime * result
            + ((getPasswordConfirmation() == null) ? 0 : getPasswordConfirmation().hashCode());
    result = prime * result + ((getAdmin() == null) ? 0 : getAdmin().hashCode());
    result = prime * result + ((getIcon() == null) ? 0 : getIcon().hashCode());
    result = prime * result + ((getTempRegistFlg() == null) ? 0 : getTempRegistFlg().hashCode());
    result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
    result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
    return result;
  }
}
