package com.app.ecotiya.domain.model;

import java.util.Date;

public class MSiteCommentKinds {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_site_comment_kinds.coment_kind_code
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private String comentKindCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_site_comment_kinds.coment_kind_name
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private String comentKindName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_site_comment_kinds.created_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_site_comment_kinds.updated_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_site_comment_kinds.coment_kind_code
     *
     * @return the value of m_site_comment_kinds.coment_kind_code
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public String getComentKindCode() {
        return comentKindCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_site_comment_kinds.coment_kind_code
     *
     * @param comentKindCode the value for m_site_comment_kinds.coment_kind_code
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setComentKindCode(String comentKindCode) {
        this.comentKindCode = comentKindCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_site_comment_kinds.coment_kind_name
     *
     * @return the value of m_site_comment_kinds.coment_kind_name
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public String getComentKindName() {
        return comentKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_site_comment_kinds.coment_kind_name
     *
     * @param comentKindName the value for m_site_comment_kinds.coment_kind_name
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setComentKindName(String comentKindName) {
        this.comentKindName = comentKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_site_comment_kinds.created_at
     *
     * @return the value of m_site_comment_kinds.created_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_site_comment_kinds.created_at
     *
     * @param createdAt the value for m_site_comment_kinds.created_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_site_comment_kinds.updated_at
     *
     * @return the value of m_site_comment_kinds.updated_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_site_comment_kinds.updated_at
     *
     * @param updatedAt the value for m_site_comment_kinds.updated_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MSiteCommentKinds other = (MSiteCommentKinds) that;
        return (this.getComentKindCode() == null ? other.getComentKindCode() == null : this.getComentKindCode().equals(other.getComentKindCode()))
            && (this.getComentKindName() == null ? other.getComentKindName() == null : this.getComentKindName().equals(other.getComentKindName()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_site_comment_kinds
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getComentKindCode() == null) ? 0 : getComentKindCode().hashCode());
        result = prime * result + ((getComentKindName() == null) ? 0 : getComentKindName().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        return result;
    }
}