package com.app.ecotiya.domain.model;

import java.util.Date;

public class MSkillDivision {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_skill_division.skill_division_id
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private Integer skillDivisionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_skill_division.skill_division_name
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private String skillDivisionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_skill_division.created_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_skill_division.updated_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_skill_division.skill_division_id
     *
     * @return the value of m_skill_division.skill_division_id
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public Integer getSkillDivisionId() {
        return skillDivisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_skill_division.skill_division_id
     *
     * @param skillDivisionId the value for m_skill_division.skill_division_id
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setSkillDivisionId(Integer skillDivisionId) {
        this.skillDivisionId = skillDivisionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_skill_division.skill_division_name
     *
     * @return the value of m_skill_division.skill_division_name
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public String getSkillDivisionName() {
        return skillDivisionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_skill_division.skill_division_name
     *
     * @param skillDivisionName the value for m_skill_division.skill_division_name
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setSkillDivisionName(String skillDivisionName) {
        this.skillDivisionName = skillDivisionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_skill_division.created_at
     *
     * @return the value of m_skill_division.created_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_skill_division.created_at
     *
     * @param createdAt the value for m_skill_division.created_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_skill_division.updated_at
     *
     * @return the value of m_skill_division.updated_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_skill_division.updated_at
     *
     * @param updatedAt the value for m_skill_division.updated_at
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MSkillDivision other = (MSkillDivision) that;
        return (this.getSkillDivisionId() == null ? other.getSkillDivisionId() == null : this.getSkillDivisionId().equals(other.getSkillDivisionId()))
            && (this.getSkillDivisionName() == null ? other.getSkillDivisionName() == null : this.getSkillDivisionName().equals(other.getSkillDivisionName()))
            && (this.getCreatedAt() == null ? other.getCreatedAt() == null : this.getCreatedAt().equals(other.getCreatedAt()))
            && (this.getUpdatedAt() == null ? other.getUpdatedAt() == null : this.getUpdatedAt().equals(other.getUpdatedAt()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table m_skill_division
     *
     * @mbg.generated Thu May 12 21:56:48 JST 2022
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSkillDivisionId() == null) ? 0 : getSkillDivisionId().hashCode());
        result = prime * result + ((getSkillDivisionName() == null) ? 0 : getSkillDivisionName().hashCode());
        result = prime * result + ((getCreatedAt() == null) ? 0 : getCreatedAt().hashCode());
        result = prime * result + ((getUpdatedAt() == null) ? 0 : getUpdatedAt().hashCode());
        return result;
    }
}