package com.app.ecotiya.domain.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TCareerExample {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_career
     * @mbg.generated
     */
    protected String orderByClause;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_career
     * @mbg.generated
     */
    protected boolean distinct;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database table t_career
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public TCareerExample () {
        oredCriteria = new ArrayList<> ();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public void setOrderByClause (String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public String getOrderByClause () {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public void setDistinct (boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public boolean isDistinct () {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria () {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public void or (Criteria criteria) {
        oredCriteria.add (criteria);
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public Criteria or () {
        Criteria criteria = createCriteriaInternal ();
        oredCriteria.add (criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public Criteria createCriteria () {
        Criteria criteria = createCriteriaInternal ();
        if (oredCriteria.size () == 0) {
            oredCriteria.add (criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal () {
        Criteria criteria = new Criteria ();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_career
     * @mbg.generated
     */
    public void clear () {
        oredCriteria.clear ();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_career
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;
        
        protected GeneratedCriteria () {
            super ();
            criteria = new ArrayList<> ();
        }
        
        public boolean isValid () {
            return criteria.size () > 0;
        }
        
        public List<Criterion> getAllCriteria () {
            return criteria;
        }
        
        public List<Criterion> getCriteria () {
            return criteria;
        }
        
        protected void addCriterion (String condition) {
            if (condition == null) {
                throw new RuntimeException ("Value for condition cannot be null");
            }
            criteria.add (new Criterion (condition));
        }
        
        protected void addCriterion (String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException ("Value for " + property + " cannot be null");
            }
            criteria.add (new Criterion (condition, value));
        }
        
        protected void addCriterion (String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException ("Between values for " + property + " cannot be null");
            }
            criteria.add (new Criterion (condition, value1, value2));
        }
        
        public Criteria andCareerIdIsNull () {
            addCriterion ("career_id is null");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdIsNotNull () {
            addCriterion ("career_id is not null");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdEqualTo (Long value) {
            addCriterion ("career_id =", value, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdNotEqualTo (Long value) {
            addCriterion ("career_id <>", value, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdGreaterThan (Long value) {
            addCriterion ("career_id >", value, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdGreaterThanOrEqualTo (Long value) {
            addCriterion ("career_id >=", value, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdLessThan (Long value) {
            addCriterion ("career_id <", value, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdLessThanOrEqualTo (Long value) {
            addCriterion ("career_id <=", value, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdIn (List<Long> values) {
            addCriterion ("career_id in", values, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdNotIn (List<Long> values) {
            addCriterion ("career_id not in", values, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdBetween (Long value1, Long value2) {
            addCriterion ("career_id between", value1, value2, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andCareerIdNotBetween (Long value1, Long value2) {
            addCriterion ("career_id not between", value1, value2, "careerId");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeIsNull () {
            addCriterion ("datetime is null");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeIsNotNull () {
            addCriterion ("datetime is not null");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeEqualTo (Date value) {
            addCriterion ("datetime =", value, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeNotEqualTo (Date value) {
            addCriterion ("datetime <>", value, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeGreaterThan (Date value) {
            addCriterion ("datetime >", value, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeGreaterThanOrEqualTo (Date value) {
            addCriterion ("datetime >=", value, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeLessThan (Date value) {
            addCriterion ("datetime <", value, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeLessThanOrEqualTo (Date value) {
            addCriterion ("datetime <=", value, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeIn (List<Date> values) {
            addCriterion ("datetime in", values, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeNotIn (List<Date> values) {
            addCriterion ("datetime not in", values, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeBetween (Date value1, Date value2) {
            addCriterion ("datetime between", value1, value2, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andDatetimeNotBetween (Date value1, Date value2) {
            addCriterion ("datetime not between", value1, value2, "datetime");
            return (Criteria) this;
        }
        
        public Criteria andTitleIsNull () {
            addCriterion ("title is null");
            return (Criteria) this;
        }
        
        public Criteria andTitleIsNotNull () {
            addCriterion ("title is not null");
            return (Criteria) this;
        }
        
        public Criteria andTitleEqualTo (String value) {
            addCriterion ("title =", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleNotEqualTo (String value) {
            addCriterion ("title <>", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleGreaterThan (String value) {
            addCriterion ("title >", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleGreaterThanOrEqualTo (String value) {
            addCriterion ("title >=", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleLessThan (String value) {
            addCriterion ("title <", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleLessThanOrEqualTo (String value) {
            addCriterion ("title <=", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleLike (String value) {
            addCriterion ("title like", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleNotLike (String value) {
            addCriterion ("title not like", value, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleIn (List<String> values) {
            addCriterion ("title in", values, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleNotIn (List<String> values) {
            addCriterion ("title not in", values, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleBetween (String value1, String value2) {
            addCriterion ("title between", value1, value2, "title");
            return (Criteria) this;
        }
        
        public Criteria andTitleNotBetween (String value1, String value2) {
            addCriterion ("title not between", value1, value2, "title");
            return (Criteria) this;
        }
        
        public Criteria andContentIsNull () {
            addCriterion ("content is null");
            return (Criteria) this;
        }
        
        public Criteria andContentIsNotNull () {
            addCriterion ("content is not null");
            return (Criteria) this;
        }
        
        public Criteria andContentEqualTo (String value) {
            addCriterion ("content =", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentNotEqualTo (String value) {
            addCriterion ("content <>", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentGreaterThan (String value) {
            addCriterion ("content >", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentGreaterThanOrEqualTo (String value) {
            addCriterion ("content >=", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentLessThan (String value) {
            addCriterion ("content <", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentLessThanOrEqualTo (String value) {
            addCriterion ("content <=", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentLike (String value) {
            addCriterion ("content like", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentNotLike (String value) {
            addCriterion ("content not like", value, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentIn (List<String> values) {
            addCriterion ("content in", values, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentNotIn (List<String> values) {
            addCriterion ("content not in", values, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentBetween (String value1, String value2) {
            addCriterion ("content between", value1, value2, "content");
            return (Criteria) this;
        }
        
        public Criteria andContentNotBetween (String value1, String value2) {
            addCriterion ("content not between", value1, value2, "content");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtIsNull () {
            addCriterion ("created_at is null");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtIsNotNull () {
            addCriterion ("created_at is not null");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtEqualTo (Date value) {
            addCriterion ("created_at =", value, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtNotEqualTo (Date value) {
            addCriterion ("created_at <>", value, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtGreaterThan (Date value) {
            addCriterion ("created_at >", value, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtGreaterThanOrEqualTo (Date value) {
            addCriterion ("created_at >=", value, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtLessThan (Date value) {
            addCriterion ("created_at <", value, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtLessThanOrEqualTo (Date value) {
            addCriterion ("created_at <=", value, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtIn (List<Date> values) {
            addCriterion ("created_at in", values, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtNotIn (List<Date> values) {
            addCriterion ("created_at not in", values, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtBetween (Date value1, Date value2) {
            addCriterion ("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andCreatedAtNotBetween (Date value1, Date value2) {
            addCriterion ("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtIsNull () {
            addCriterion ("updated_at is null");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtIsNotNull () {
            addCriterion ("updated_at is not null");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtEqualTo (Date value) {
            addCriterion ("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtNotEqualTo (Date value) {
            addCriterion ("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtGreaterThan (Date value) {
            addCriterion ("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtGreaterThanOrEqualTo (Date value) {
            addCriterion ("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtLessThan (Date value) {
            addCriterion ("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtLessThanOrEqualTo (Date value) {
            addCriterion ("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtIn (List<Date> values) {
            addCriterion ("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtNotIn (List<Date> values) {
            addCriterion ("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtBetween (Date value1, Date value2) {
            addCriterion ("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
        
        public Criteria andUpdatedAtNotBetween (Date value1, Date value2) {
            addCriterion ("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator. This class corresponds to the database table t_career
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;
        private Object value;
        private Object secondValue;
        private boolean noValue;
        private boolean singleValue;
        private boolean betweenValue;
        private boolean listValue;
        private String typeHandler;
        
        public String getCondition () {
            return condition;
        }
        
        public Object getValue () {
            return value;
        }
        
        public Object getSecondValue () {
            return secondValue;
        }
        
        public boolean isNoValue () {
            return noValue;
        }
        
        public boolean isSingleValue () {
            return singleValue;
        }
        
        public boolean isBetweenValue () {
            return betweenValue;
        }
        
        public boolean isListValue () {
            return listValue;
        }
        
        public String getTypeHandler () {
            return typeHandler;
        }
        
        protected Criterion (String condition) {
            super ();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }
        
        protected Criterion (String condition, Object value, String typeHandler) {
            super ();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }
        
        protected Criterion (String condition, Object value) {
            this (condition, value, null);
        }
        
        protected Criterion (String condition, Object value, Object secondValue, String typeHandler) {
            super ();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }
        
        protected Criterion (String condition, Object value, Object secondValue) {
            this (condition, value, secondValue, null);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_career
     *
     * @mbg.generated do_not_delete_during_merge Thu May 12 21:56:48 JST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }
}