package com.app.ecotiya.domain.model;

import java.util.Date;

public class TInquiryLists {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.inquiry_id
     * @mbg.generated
     */
    private Long inquiryId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.name
     * @mbg.generated
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.mail_address
     * @mbg.generated
     */
    private String mailAddress;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.inquiry_kind_code
     * @mbg.generated
     */
    private String inquiryKindCode;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.created_at
     * @mbg.generated
     */
    private Date createdAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.updated_at
     * @mbg.generated
     */
    private Date updatedAt;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_inquiry_lists.contents
     * @mbg.generated
     */
    private String contents;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.inquiry_id
     * @return  the value of t_inquiry_lists.inquiry_id
     * @mbg.generated
     */
    public Long getInquiryId () {
        return inquiryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.inquiry_id
     * @param inquiryId  the value for t_inquiry_lists.inquiry_id
     * @mbg.generated
     */
    public void setInquiryId (Long inquiryId) {
        this.inquiryId = inquiryId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.name
     * @return  the value of t_inquiry_lists.name
     * @mbg.generated
     */
    public String getName () {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.name
     * @param name  the value for t_inquiry_lists.name
     * @mbg.generated
     */
    public void setName (String name) {
        this.name = name == null ? null : name.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.mail_address
     * @return  the value of t_inquiry_lists.mail_address
     * @mbg.generated
     */
    public String getMailAddress () {
        return mailAddress;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.mail_address
     * @param mailAddress  the value for t_inquiry_lists.mail_address
     * @mbg.generated
     */
    public void setMailAddress (String mailAddress) {
        this.mailAddress = mailAddress == null ? null : mailAddress.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.inquiry_kind_code
     * @return  the value of t_inquiry_lists.inquiry_kind_code
     * @mbg.generated
     */
    public String getInquiryKindCode () {
        return inquiryKindCode;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.inquiry_kind_code
     * @param inquiryKindCode  the value for t_inquiry_lists.inquiry_kind_code
     * @mbg.generated
     */
    public void setInquiryKindCode (String inquiryKindCode) {
        this.inquiryKindCode = inquiryKindCode == null ? null : inquiryKindCode.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.created_at
     * @return  the value of t_inquiry_lists.created_at
     * @mbg.generated
     */
    public Date getCreatedAt () {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.created_at
     * @param createdAt  the value for t_inquiry_lists.created_at
     * @mbg.generated
     */
    public void setCreatedAt (Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.updated_at
     * @return  the value of t_inquiry_lists.updated_at
     * @mbg.generated
     */
    public Date getUpdatedAt () {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.updated_at
     * @param updatedAt  the value for t_inquiry_lists.updated_at
     * @mbg.generated
     */
    public void setUpdatedAt (Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_inquiry_lists.contents
     * @return  the value of t_inquiry_lists.contents
     * @mbg.generated
     */
    public String getContents () {
        return contents;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_inquiry_lists.contents
     * @param contents  the value for t_inquiry_lists.contents
     * @mbg.generated
     */
    public void setContents (String contents) {
        this.contents = contents == null ? null : contents.trim ();
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated
     */
    @Override
    public boolean equals (Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass () != that.getClass ()) {
            return false;
        }
        TInquiryLists other = (TInquiryLists) that;
        return (this.getInquiryId () == null ? other.getInquiryId () == null
                : this.getInquiryId ().equals (other.getInquiryId ()))
                && (this.getName () == null ? other.getName () == null : this.getName ().equals (other.getName ()))
                && (this.getMailAddress () == null ? other.getMailAddress () == null
                        : this.getMailAddress ().equals (other.getMailAddress ()))
                && (this.getInquiryKindCode () == null ? other.getInquiryKindCode () == null
                        : this.getInquiryKindCode ().equals (other.getInquiryKindCode ()))
                && (this.getCreatedAt () == null ? other.getCreatedAt () == null
                        : this.getCreatedAt ().equals (other.getCreatedAt ()))
                && (this.getUpdatedAt () == null ? other.getUpdatedAt () == null
                        : this.getUpdatedAt ().equals (other.getUpdatedAt ()))
                && (this.getContents () == null ? other.getContents () == null
                        : this.getContents ().equals (other.getContents ()));
    }

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table t_inquiry_lists
     * @mbg.generated
     */
    @Override
    public int hashCode () {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getInquiryId () == null) ? 0 : getInquiryId ().hashCode ());
        result = prime * result + ((getName () == null) ? 0 : getName ().hashCode ());
        result = prime * result + ((getMailAddress () == null) ? 0 : getMailAddress ().hashCode ());
        result = prime * result + ((getInquiryKindCode () == null) ? 0 : getInquiryKindCode ().hashCode ());
        result = prime * result + ((getCreatedAt () == null) ? 0 : getCreatedAt ().hashCode ());
        result = prime * result + ((getUpdatedAt () == null) ? 0 : getUpdatedAt ().hashCode ());
        result = prime * result + ((getContents () == null) ? 0 : getContents ().hashCode ());
        return result;
    }
}